create or alter procedure sp_dim_produto(@data_carga datetime)
as
begin
DECLARE @COD_PRODUTO INT,
		@PRODUTO VARCHAR(100),
		@COD_CATEGORIA INT,
		@CATEGORIA VARCHAR(100),
		@PRODUTO_AUX VARCHAR(100),
		@COD_CATEGORIA_AUX INT,
		@CATEGORIA_AUX VARCHAR(100)

		DECLARE C_PRODUTO  CURSOR FOR 
		SELECT COD_PRODUTO, PRODUTO, COD_CATEGORIA, CATEGORIA FROM TB_AUX_PRODUTO

		OPEN C_PRODUTO
		FETCH C_PRODUTO INTO @COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA


		WHILE @@FETCH_STATUS = 0
		BEGIN
			IF NOT EXISTS (SELECT 1 FROM DIM_PRODUTO WHERE COD_PRODUTO = @COD_PRODUTO)
			BEGIN
					INSERT INTO DIM_PRODUTO(COD_PRODUTO,PRODUTO,COD_CATEGORIA,CATEGORIA)
					VALUES (@COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA)
			END
			ELSE
			BEGIN
					SELECT @PRODUTO_AUX = P.PRODUTO, @COD_CATEGORIA_AUX = P.COD_CATEGORIA, @CATEGORIA_AUX = P.CATEGORIA
					FROM DIM_PRODUTO P
					WHERE P.COD_PRODUTO = @COD_PRODUTO

					IF @PRODUTO_AUX <> @PRODUTO OR @COD_CATEGORIA_AUX <> @COD_CATEGORIA OR @CATEGORIA_AUX <> @CATEGORIA
					BEGIN
						UPDATE DIM_PRODUTO
						SET PRODUTO = @PRODUTO,COD_CATEGORIA = @COD_CATEGORIA,CATEGORIA = @CATEGORIA
						WHERE COD_PRODUTO = @COD_PRODUTO

						INSERT INTO DIM_PRODUTO(COD_PRODUTO, PRODUTO,COD_CATEGORIA,CATEGORIA)
						VALUES (@COD_PRODUTO,@PRODUTO,@COD_CATEGORIA,@CATEGORIA)
					END
			END
		FETCH C_PRODUTO INTO @COD_PRODUTO, @PRODUTO, @COD_CATEGORIA, @CATEGORIA
		END
	CLOSE C_PRODUTO
	DEALLOCATE C_PRODUTO
end


-- Teste

exec sp_dim_produto '20230321'

select * from dim_produto
select * from tb_aux_produto