create or alter procedure sp_dim_loja(@data_carga datetime)
as
begin
	DECLARE @COD_LOJA INT,
			@LOJA VARCHAR(100),
			@CIDADE VARCHAR(100),
			@ESTADO VARCHAR(100),
			@SIGLA_ESTADO VARCHAR(2),
			@LOJA_AUX VARCHAR(100),
			@CIDADE_AUX VARCHAR(100),
			@ESTADO_AUX VARCHAR(100),
			@SIGLA_ESTADO_AUX VARCHAR(2)

		DECLARE C_LOJA  CURSOR FOR 
		SELECT COD_LOJA, LOJA, CIDADE, ESTADO, SIGLA_ESTADO FROM TB_AUX_LOJA

		OPEN C_LOJA
		FETCH C_LOJA INTO @COD_LOJA, @LOJA, @CIDADE, @ESTADO, @SIGLA_ESTADO


		WHILE @@FETCH_STATUS = 0
		BEGIN
			IF NOT EXISTS (SELECT 1 FROM DIM_LOJA WHERE COD_LOJA = @COD_LOJA)
			BEGIN
					INSERT INTO DIM_LOJA(COD_LOJA, LOJA, CIDADE, ESTADO, SIGLA_ESTADO)
					VALUES(@COD_LOJA, @LOJA, @CIDADE, @ESTADO, @SIGLA_ESTADO)
			END
			ELSE
			BEGIN
					SELECT @LOJA_AUX = L.LOJA, @CIDADE_AUX = L.CIDADE, @ESTADO_AUX = L.ESTADO, @SIGLA_ESTADO_AUX = L.SIGLA_ESTADO
					FROM DIM_LOJA L
					WHERE L.COD_LOJA = @COD_LOJA

					IF @LOJA_AUX <> @LOJA OR @CIDADE_AUX <> @CIDADE OR @ESTADO_AUX <> @ESTADO
					BEGIN
						UPDATE DIM_LOJA
						SET LOJA = @LOJA,CIDADE = @CIDADE,ESTADO = @ESTADO,SIGLA_ESTADO = @SIGLA_ESTADO
						WHERE COD_LOJA = @COD_LOJA

						INSERT INTO DIM_LOJA(COD_LOJA, LOJA, CIDADE, ESTADO, SIGLA_ESTADO)
						VALUES(@COD_LOJA, @LOJA, @CIDADE, @ESTADO, @SIGLA_ESTADO)
					END
			END
		FETCH C_LOJA INTO @COD_LOJA, @LOJA, @CIDADE, @ESTADO, @SIGLA_ESTADO
		END
	CLOSE C_LOJA
	DEALLOCATE C_LOJA
end

-- Teste

exec sp_dim_loja '20230321'

select * from dim_loja
select * from TB_AUX_LOJA
select * from TB_LOJA

