use dw_lowlatency

create or alter procedure sp_dim_tipo_pagamento(@data_carga datetime)
as
begin
		DECLARE @COD_TIPO_PAGAMENTO INT,
				@TIPO_PAGAMENTO VARCHAR(100),
				@TIPO_PAGAMENTO_AUX VARCHAR(100)

		DECLARE C_TIPO_PAGAMENTO CURSOR FOR 
		SELECT COD_TIPO_PAGAMENTO, TIPO_PAGAMENTO FROM TB_AUX_TIPO_PAGAMENTO

		OPEN C_TIPO_PAGAMENTO
		FETCH C_TIPO_PAGAMENTO INTO @COD_TIPO_PAGAMENTO, @TIPO_PAGAMENTO


		WHILE @@FETCH_STATUS = 0
		BEGIN
			IF NOT EXISTS (SELECT * FROM DIM_TIPO_PAGAMENTO WHERE COD_TIPO_PAGAMENTO = @COD_TIPO_PAGAMENTO)
			BEGIN
					INSERT INTO DIM_TIPO_PAGAMENTO(COD_TIPO_PAGAMENTO,TIPO_PAGAMENTO)
					VALUES (@COD_TIPO_PAGAMENTO, @TIPO_PAGAMENTO)
			END
			ELSE
			BEGIN
					SELECT @TIPO_PAGAMENTO_AUX = P.TIPO_PAGAMENTO
					FROM DIM_TIPO_PAGAMENTO P
					WHERE P.COD_TIPO_PAGAMENTO = @COD_TIPO_PAGAMENTO

					IF @TIPO_PAGAMENTO_AUX <> @TIPO_PAGAMENTO
					BEGIN
						UPDATE DIM_TIPO_PAGAMENTO
						SET TIPO_PAGAMENTO = @TIPO_PAGAMENTO

						INSERT INTO DIM_TIPO_PAGAMENTO(COD_TIPO_PAGAMENTO, TIPO_PAGAMENTO)
						VALUES (@COD_TIPO_PAGAMENTO,@TIPO_PAGAMENTO)
					END
			END
			FETCH C_TIPO_PAGAMENTO INTO @COD_TIPO_PAGAMENTO, @TIPO_PAGAMENTO
		END
	CLOSE C_TIPO_PAGAMENTO
	DEALLOCATE C_TIPO_PAGAMENTO
end



-- Teste

exec sp_dim_tipo_pagamento '20230321'

select * from dim_tipo_pagamento
SELECT * FROM TB_TIPO_PAGAMENTO