create or alter procedure sp_fato_venda_loja_mensal
as
begin
		DECLARE @ID_TEMPO BIGINT,
				@MES INT,
				@ANO INT,
				@ID_LOJA INT,
				@VOLUME NUMERIC(10,2),
				@VALOR NUMERIC(10,2)

		DELETE FROM FATO_VENDA_LOJA_MENSAL

		DECLARE C_VENDA_LOJA_MENSAL CURSOR FOR
		SELECT ID_TEMPO, MES, ANO
		FROM DIM_TEMPO
		WHERE NIVEL = 'MES'

		

		OPEN C_VENDA_LOJA_MENSAL
		FETCH NEXT FROM C_VENDA_LOJA_MENSAL INTO @ID_TEMPO,@MES, @ANO

		WHILE @@FETCH_STATUS = 0
		BEGIN
				INSERT INTO FATO_VENDA_LOJA_MENSAL
				SELECT @ID_TEMPO,V.ID_LOJA,SUM(V.VOLUME), SUM(V.VALOR), SUM(V.QUANTIDADE)
				FROM FATO_VENDA V
				INNER JOIN DIM_TEMPO T ON V.ID_TEMPO = T.ID_TEMPO
				WHERE MONTH(T.DATA) = @MES AND YEAR(T.DATA) = @ANO
				GROUP BY V.ID_LOJA

			FETCH NEXT FROM C_VENDA_LOJA_MENSAL INTO @ID_TEMPO,@MES, @ANO
		END
	CLOSE C_VENDA_LOJA_MENSAL
	DEALLOCATE C_VENDA_LOJA_MENSAL
end

-- Teste

exec sp_fato_venda_loja_mensal

SELECT * FROM FATO_VENDA_LOJA_MENSAL

SELECT * FROM FATO_VENDA

SELECT * FROM DIM_TEMPO
